bagrinsergiu/MB-migration

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
This update includes a more comprehensive evaluation of the 'link' element in items for Theme/Anthem. Now, it not only checks whether the link field is non-empty, but also validates its existence before performing a check. This prevents potential undefined index issues.
> Refine check for item link in Head.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Core/ErrorDump.php
The 'removePx' method used in the theme file was replaced with PHP's built-in 'str_replace' function. This change reduces the complexity and improves the efficiency of the theme's opacity set function. Also, the calling of 'getCache' function in the 'ErrorDump' service has been commented out temporarily for debugging purposes.
> Replace 'removePx' method with 'str_replace'

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/SmallGroupsList.php
Removing the unnecessary object instantiation also potentially optimizes memory usage.
> Remove unused instance of ItemBuilder in SmallGroupsList

- lib/MBMigration/Browser/Browser.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/ListLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/RightMedia.php
The Puppeteer options in the browser constructor have been extended. A protocolTimeout has been added with a value of 120000 to handle longer lasting operations without throwing a timeout error.
> Added protocolTimeout to Puppeteer options

- lib/MBMigration/Layer/MB/MBProjectDataCollector.php
- lib/MBMigration/MigrationPlatform.php
Removed several methods in MigrationPlatform.php and MBProjectDataCollector.php which were used to manage color palettes. These methods were deleted because they are not used anywhere in the current code, making the code cleaner and leaner. Code blocks that were commented out were also removed to enhance clarity.
> Remove color palette related functions

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
Extended the layout builder functionality in the 'Anthem' theme by providing new submenu styling options. Three new definitions for submenu hover background color, submenu color, and submenu color opacity have been added to the default options array.
> Add submenu styling options to layout builder

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
The default layout theme options have been tweaked for better design consistency. Specifically, the active submenu color opacity was set to full, and the submenu color opacity was slightly reduced. These changes aim to improve visual appeal and enhance display on various devices.
> Adjust active and sub menu opacity in theme layout

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/FullText.php
This commit introduces the functionality to extract and apply styles to the donation button in the theme builder. Two new methods, `ExtractStyleDonateButton` and `ExtractStyleDonateButtonStyle`, have been created to handle the extraction process while a transformation method in the `FullText.php` file has been updated to apply the extracted styles. This will ensure the donation button maintains consistent styles and aesthetics across different pages of the website.
> Implement donation button style extraction in theme builder

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventCalendarLayout.php
This commit adds additional background color settings for mobile view in the EventCalendarLayout. The newly introduced settings allow to set the background color hex code specifically for mobile devices, providing a better visual experience for mobile users. The settings options are 'mobileBgColorPalette' and 'mobileBgColorHex'.
> Add mobile background color settings in EventCalendarLayout

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventGalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventGridLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventListLayout.php
Updated the EventGridLayout, EventGalleryLayout, and EventListLayout files in the Anthem theme to include settings for mobile background color palette and hex. This enhancement ensures consistency and flexibility in color settings across devices.
> Add mobile background color settings in layout themes.

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
The if condition for 'new_window' has been updated in the Element.php file. Previously, the condition was checking for not 'new_window'. Now it explicitly checks if 'new_window' is set to true, improving readability and precision.
> Refactor new_window condition check in Element.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
The code for processing URLs has been extracted into a new private function, processURL(). This function checks if a URL has a host or a valid scheme, and then returns either an empty string or a slash accordingly. This mitigates the code redundancy and makes the Element class cleaner and more maintainable.
> Refactor URL processing into separate function

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
The opacity key name under style was changed from 'opacity_div' to 'opacity'. The change reflects the updated structure of the data passed to the 'Element' class. This ensures that the opacity value is correctly extracted and processed.
> Update opacity key name in Element.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
This commit adds functionality to ignore hidden items while building the menu tree in the layout builder. It further modifies the URL assignment process to ensure it only picks up non-hidden items from child list, thus improving responsiveness and correctness of the menu tree.
> Skip hidden menu items in layout builder

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
The path to 'opacity' property was incorrect and would have caused errors during theme migration. This commit fixes the path, ensuring that the opacity value of a background element is correctly fetched and processed.
> Update path to 'opacity' in Element.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/GalleryLayout.php
Additional color attributes for the slider dots have been added to the GalleryLayout in the Anthem theme. The added configurations allow control over the color, opacity, and color palette of both the slider dots and their hover state.
> Add slider dots color configuration in GalleryLayout

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
In the Anthem Theme, we have changed how we handle the listItem variable within the foreach loop. Now, by referencing the listItem, we are able to directly modify the original array during each iteration.
> Refactor listItem in foreach loop to reference

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Dom/index.ts
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/StyleExtractor/index.ts
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/index.ts
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/src/Dom/index.ts
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/src/StyleExtractor/index.ts
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/src/index.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/Dom/index.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/StyleExtractor/index.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/index.ts
- packages/elements/src/Dom/getNodeText.ts
- packages/elements/src/Dom/hasNode.ts
- packages/elements/src/StyleExtractor/index.ts
The StyleExtractor module has been enhanced by adding two new functions, hasNode and getNodeText. These functions check if an HTML node exists, and if it does, they retrieve its text content. The new functions have also been imported into the various theme asset libraries for further use.
> Add hasNode and getNodeText functions to StyleExtractor

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/GalleryLayout.php
Updated the GalleryLayout to support background videos when set in the section data. The code now checks for the presence of a 'video' setting in the background section, and if found, inserts an element with the needed properties into the block array. The code handles section items in the else clause, preserving existing functionality.
> Add support for background video in GalleryLayout

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Dom/index.ts
- packages/elements/src/Dom/detectSubpalette.ts
A new file named detectSubpalette.ts has been added to the Dom package in the elements/src which contains a new function called detectSubpalette. This function helps to detect subpalettes in a given HTML selector. Additionally, it's been imported and added to the object export in the Dom/index.ts file.
> feat(Subpalette): function to DOM package

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/GridMediaLayout.php
This commit introduces a conditional check for the 'mediaGridContainer' setting in the GridMediaLayout. If the setting is false, the 'searchValue' is set to the value of 'containTitle' from the section data.
> Add conditional check for mediaGridContainer setting

- lib/MBMigration/Browser/BrowserPHP.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/GridMediaLayout.php
The commit modifies the `GridMediaLayout.php` file, changing the source of `titleColorHex` and `hoverTitleColorHex` to be from 'palette' instead of 'sermon'. Also, in the `BrowserPHP.php` file, the navigation wait type was updated from 'LOAD' to 'NETWORK_IDLE'. An explicit newline was added at the end of the document as well to adhere to good coding standards.
> Update title color source and navigation type

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
- lib/MBMigration/Builder/Utils/ColorUtility.php
Renamed the `createDetailPage` method to `createEventDetailPage` for specificity and clarity within Anthem elements. Updated the layout settings and parameters to accommodate both event and sermon page types. Also, improved the `ColorUtility` class to correctly translate short-form hex color codes into their full six-digit counterparts.
> Refactor detail page and color utility in MBMigration

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/GridMediaLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/ListMediaLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
The commit involves the renaming of createDetailPage to createSermonsDetailPage for clarity. Changes in settings of the detail page include turning on 'showSubscribeToEvent' option, adding 'subscribeEventButton' options and altering visibility of various elements. This provides a more detailed and specific configuration for Sermons Detail Page.
> Update settings for Sermons Detail Page

- lib/MBMigration/Builder/Layout/Common/Concern/RichTextAble.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/FourHorizontalText.php
A button selector variable has been introduced in the FourHorizontalText component to handle the rich text item. Additionally, the HTML parsing flags in the RichTextAble class have been updated to include LIBXML_NOWARNING, helping to suppress warning messages during the DOM creation process.
> Add button selector in FourHorizontalText component

- packages/elements/src/Menu/getMenuItem.ts
- packages/elements/src/Menu/getSubMenuItem.ts
- packages/elements/src/Menu/utils/getModel.ts
- packages/elements/src/Menu/utils/toMenuItemElement.ts
| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/344 |
> 1. Mobile - can the menu icon be white, so it matches the clover example? It's not really visible with the current color: https://prnt.sc/X97gTOsjfR9t @zeleniucvladislav
>2. On the clover site, the selected main navigation item shows the hover color as the active color. Can we do the same with the hover/active state on the Brizy site? @zeleniucvladislav
> 3. For the nav on this site, the hover/active color should be white. The white color is showing on hover for the main nav items, but not for the dropdown. @zeleniucvladislav
>  2. 2. The menu items aren't visible: https://prnt.sc/OqO1bZwq2T0q, https://timberwoodchurch-31706.mydraftsite.cloud/ …
> fix(menu): menu hover and mobile menu icon color

- packages/elements/src/Menu/getMenuItem.ts
| Q  | A |
| Screenshot  |  ![2024-09-09_11-25](https://github.com/user-attachments/assets/f6db2cb2-1cb7-4c22-b249-2308cf2368a3)|
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/389 |
Related to : 
>  2. The mobile menu items need to be a lighter color: https://prnt.sc/HBJfNwZ8QIW0. See the current clover site: https://prnt.sc/D54gOIsS-vpA
> fix(menu) : added tablet/mobile mMenu colorhex

- packages/elements/src/Menu/utils/getModel.ts
| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/344 |
> For for top/main menu bar on desktop, I'm still seeing the tighter spacing here: https://prnt.sc/S-MQSjcmh2d-. It looks like this is still showing at 7.5px for both left/right margin. Can we change this to 10px? I think that should be fine.
Brizy item spacing 15px result in left 7.5 and right 7.5
Ministrybrands ahs both spacing 15px on left and right 
* Fixed: Menu item spacing incorrect value
> fix(menu): item spacing too small

- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
Updated the conditional check for media layout sections to properly handle cases where 'mediaGridContainer' is not present. This ensures that the correct BrizyComponent elements are added based on the presence or absence of 'mediaGridContainer'.
> Fix media layout section condition check

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
Refine selectors for sub-navigation items to exclude selected items. Adjust mobile menu item selector to target specific navigation links. Revert mobile button selector to its original state.
> Update CSS selectors for theme menu elements

- lib/MBMigration/Builder/Layout/Common/Element/Events/EventLayout.php
Replaced 'btn-bg' and 'btn' with 'bg' for the calendar background color hex and 'btn-text' with 'text' for the calendar days color hex. This aligns with the new section palette structure.
> Update color palette keys in EventLayout

- lib/MBMigration/Builder/PageController.php
Added a check for empty gallery lists to prevent errors when no items are found. This ensures the 'slide' key is handled properly even if the 'list' key doesn't exist, improving data integrity and avoiding potential crashes in the gallery section rendering.
> Handle empty gallery list in PageController.

- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
This update introduces `DETAILS_PAGE_NAME` and `DETAILS_SLUG_NAME` constants to replace hardcoded values in the `MediaLayout` class. This change enhances code maintainability and readability by using named constants for repeated strings.
> Add sermon detail constants for page and slug names

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Menu/utils/getModel.ts
| Q  | A |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/434|
* Refactored:  added child padding for itemPadding key
> refactor(menu): added child padding for itemPadding key

- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
Updated MediaLayout to include item background color and default opacity settings. This enhancement ensures that both the section and its description have consistent styling properties.
> Add background color and opacity settings for section items

- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
Correct variable name from `sectionDiscriptionStyle` to `sectionDescriptionStyle` to prevent potential errors. Add new style configurations for section player and description items to enhance media layout customization.
> Fix typo in variable name and add styles for media layout.

- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
Updated MediaLayout to correct colorHex fallback value to handle opacity. Introduced new style options for active menu items in Head.php, including border styles and colors.
> Fix colorHex fallback and add active menu styles

- lib/MBMigration/Builder/Layout/Common/Elements/Gallery/GalleryLayoutElement.php
Changed condition to check 'slide' count instead of 'items' count to determine autoplay behavior. This ensures correct autoplay setting when there is only one slide.
> Fix autoplay condition in GalleryLayoutElement

- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
Correct the key reference for 'activePaginationColorOpacity' to ensure the opacity value is accurately retrieved. This change swaps the order of the fallback values, fixing potential issues with opacity settings in pagination.
> Fix active pagination color opacity assignment

- lib/MBMigration/Builder/Layout/Common/Concern/SectionStylesAble.php
If the background opacity is 0.9 or greater, set it to 0.6 to ensure visual consistency in sections. This change improves readability and design aesthetics when dealing with images that have high opacity values.
> Adjust background opacity for high-opacity images

- lib/MBMigration/Builder/Layout/Common/Concern/RichTextAble.php
Previously, the new window option for links was not processed. This update ensures that the 'new_window' attribute is properly set to 'on' or 'off' based on its value.
> Handle new window option in handleLink method

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
Adjust the mobile size to 100% when there's only one item in a row. This ensures a full-width display on mobile devices, improving the layout responsiveness.
> Add mobile size for single item rows in GridLayoutElement

- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventLayoutElement.php
This commit introduces a switch statement to set the event view order dynamically based on the 'typeSection' value of the 'mbSection' array. Default view orders are defined for both 'event-tile-layout' and other section types. Additionally, the new eventTabs array is merged into the sectionProperties to apply the correct ordering.
> Adjust event view order based on the section type

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Sermons/MediaLayoutElement.php
Introduced a new method `internalTransformToItem` that incorporates a wrapper line component with a dynamic border color. The color is extracted using Brizy's script evaluation, converted to hex, and then applied to the wrapper line before being added to the Brizy section.
> Add wrapper line with border color to Sermons MediaLayoutElement

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Menu/getMenuItem.ts
- packages/elements/src/Menu/getSubMenuItem.ts
- packages/elements/src/Menu/utils/getModel.ts
- packages/elements/src/Tabs/__tests__/getTabs.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
- packages/elements/src/utils/getModel.ts
- packages/utils/src/dicKeyForDevices.ts
| Q  | A |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/479 |
> * Fixed: RichText Icon spacing
https://github.com/bagrinsergiu/MB-migration/pull/404/files#diff-5824251c727af26032702e76456fed4ad1865b1b97b9aca11b37f98bf733e2ddR275-R277
by removing an empty space which had an overall height of 40 px
* Fixed: RichText Icon spacing
* Improved : Added Italic value to menu
> refactor(menu): added italic value

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/utils/styles/copyParentColorToChild.ts
| Q  | A |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/471|
* Fixed: Anthem link color
> fix(richtext): appendStylesNode incorrect style node

- lib/MBMigration/Builder/Layout/Common/Concern/DanationsAble.php
- lib/MBMigration/Builder/Layout/Common/Concern/SectionStylesAble.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventFeturedLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventGalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventListLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventTileLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Forms/Form.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Forms/FullWidthForm.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Forms/LeftForm.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Forms/RightForm.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Gallery/GalleryLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Groups/SmallGroupsListElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Prayer/PrayerFormElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/AccordionLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/FullMediaElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/FullText.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/LeftMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/RightMedia.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/TabsLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/ThreeTopMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/TwoHorizontalText.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/TwoRightMediaCircle.php
Standardize the top padding for the first element across multiple layout elements by setting it to 0 instead of 50. This change affects various components like forms, text layouts, and event layouts ensuring uniform spacing across the application.
> Adjust top padding of the first element to 0

- lib/MBMigration/Browser/BrowserPagePHP.php
Updated the path where the page screenshot is saved from '/project/var/page.jpg' to '/project/var/cache/page.jpg'. This change organizes screenshots better by placing them in the cache directory.
> Change screenshot save path

- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
Refactor the logic to determine the presence of 'mediaGridContainer' and 'media-player' elements. Introduced conditional checks to enhance flexibility in detecting 'media-grid-container' or 'media-list-container' nodes. Ensure 'media-player' status is accurately set based on node presence.
> Revise media container node selection logic

- lib/MBMigration/Builder/Layout/Common/Concern/DonationsAble.php
Add a check to initialize the donation button text to 'MAKE A DONATION' if it is empty. This ensures consistent button labeling and prevents display issues when the text is not provided.
> fix: set default donation button text if empty

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
Add logic to skip elements with 'display: none' in GridLayoutElement. This ensures that hidden items do not affect layout processing, improving migration efficiency and output accuracy.
> feat: skip hidden grid items during migration

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
Introduce a new configuration option `mobileWidth` set to 100 for the GridLayoutElement. This change aims to improve mobile responsiveness by ensuring consistent element widths across devices. The additional setting will enhance layout flexibility and adaptability for different screen sizes.
> feat: add mobileWidth setting to GridLayoutElement

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Head.php
Introduce `addCustomCSS` method to BrizyComponent for adding custom CSS. Additionally, apply custom CSS for Brizy sections in the Ember theme Head element.
> feat: add support for custom CSS in Brizy components

- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/AccordionLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FourHorizontalText.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FullText.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/LeftMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/RightMedia.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/RightMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/TabsLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/ThreeBottomMediaCircle.php
Adjusted `mobilePaddingBottom` values from 0 to 25px for multiple layout elements to improve mobile styling consistency. Added missing `getPropertiesMainSection` method in `EventLayoutElement` for better configuration handling.
> fix: update mobile padding bottom to 25px across elements

- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/AccordionLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FourHorizontalText.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FullText.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/LeftMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/RightMedia.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/RightMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/TabsLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/ThreeBottomMediaCircle.php
feat: standardize top padding for layout elements
Added or updated `getTopPaddingOfTheFirstElement` method across multiple layout elements to return a consistent value of 95. This ensures uniform spacing and a more cohesive layout presentation throughout the application.
> standardize top padding for layout elements

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FourHorizontalText.php
Introduce a `canShowButton` method to control the visibility of buttons based on section settings. Update `FourHorizontalText` to include buttons in the layout when applicable, improving flexibility and customization in the layout rendering.
> feat: add button rendering logic to layout elements

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventDetailsPageLayout.php
Introduced a new `previewTypography` method in `BrizyComponent` to handle typography styling for preview elements. Integrated this functionality within `EventDetailsPageLayout` to enhance typography customization options.
> feat: add previewTypography support to event details layout

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/GridLayoutElement.php
Introduced a new handleItemRowComponent method to standardize padding behavior across GridLayoutElement classes. Refactored existing padding logic to utilize this method, improving consistency and maintainability.
> feat(padding): add reusable handleItemRowComponent method

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
Introduce globalTransformSection to apply custom CSS for buttons. Ensures proper white-space handling on smaller screens for improved responsiveness. This enhancement affects components transformed in AbstractElement.
> feat: add globalTransformSection for responsive button styles

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/SermonDetailsPageLayout.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Semons/MediaLayoutElement.php
Introduces a new `SermonDetailsPageLayout` class to handle sermon details page styles consistently. Refactors related code to utilize the new layout and adjusts padding configurations for desktop and mobile views. Includes typography and palette enhancements for better readability and customization.
> feat: add SermonDetailsPageLayout for detailed page styling

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
Introduce a method to validate background photo presence in sections. Update the switch-case logic to handle empty background content and improve layout processing behavior.
> feat: add check for empty background content section

- lib/MBMigration/Browser/BrowserPagePHP.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Head.php
Updated CSS selectors to simplify and remove unnecessary '>' combinators for clarity and consistency. Commented out an unused mouse movement call that was redundant in the hover event handling method.
> refactor: update CSS selectors and comment out unused code

- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Head.php
Updated `marginTop` and `marginBottom` values to improve layout consistency. Added padding to the first section to enhance spacing and visual alignment in the Bloom theme.
> fix: adjust margin and add padding to Bloom theme elements

- lib/MBMigration/Builder/Layout/Common/Concern/CssPropertyExtractorAware.php
- lib/MBMigration/Builder/Layout/Common/Concern/RichTextAble.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Dom/index.ts
- packages/elements/src/Dom/getNodeAttribute.ts
Introduce a new `getNodeAttribute` utility function to retrieve DOM node attributes. Updated the `handleLink` logic to utilize this utility for determining link behavior based on the `target` attribute, allowing more dynamic and accurate handling of links in different contexts.
> feat: add getNodeAttribute utility and enhance handleLink logic

- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/AccordionLayoutElement.php
This commit introduces a new style configuration, `accordionHeadTextStyle`, to set specific mobile margin values for accordion headings. These styles include top, bottom, left, and right margins with appropriate suffixes, applied via a foreach loop targeting accordion heading elements.
> Add mobile margin styles for accordion headings

- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Events/EventGalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Forms/FullWidthForm.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Forms/LeftForm.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Forms/RightForm.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Prayer/PrayerFormElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Semons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/AccordionLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/FullMediaElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/FullText.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/LeftMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/RightMedia.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/RightMediaCircle.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/TabsLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/TwoRightMediaCircle.php
- lib/MBMigration/Builder/PageController.php
Reduced the top padding offset for header height from 50 to 25 (or 30 for FullText) across various layout elements. This ensures better alignment and consistent spacing within themes. Also reformatted the PageController constructor for improved readability.
> fix: adjust top padding calculations across multiple elements

- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventGalleryLayout.php
Introduce support for `colorHex`, `colorOpacity`, and related hover configurations to enhance customization of gallery sections. Also adds new properties for `metaLinks` and their hover states, improving flexibility in link styling.
> Add additional color configuration options for EventGallery

- Dockerfile
Switched to a more reliable mirror for downloading Google Chrome. This ensures better availability and avoids potential issues with the previous URL.
> chore(Dockerfile): update Chrome download URL

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Sermons/MediaLayoutElement.php
Introduced `addHeight` and `addSectionHeight` methods to BrizyComponent for customizing height settings. Updated MediaLayoutElement to set a default section height of 100vh during transformation.
> feat: add height configuration for Brizy components

- lib/MBMigration/Builder/Layout/Common/Concern/DonationsAble.php
- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/FullMediaElementElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/FullTextElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/PhotoTextElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/FullMediaElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/FullText.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/LeftMedia.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/LeftMediaOverlap.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/RightMedia.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/RightMediaOverlap.php
Introduces a `getDonationsButtonOptions` method to allow specifying custom mobile padding for donation buttons in various elements. Default and theme-specific padding configurations are now supported, improving layout flexibility.
> feat: add customizable donations button padding options

- lib/MBMigration/Builder/Layout/Common/Concern/SectionStylesAble.php
- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Sermons/MediaLayoutElement.php
Introduced a `getHeightTypeHandleSectionStyles` method to define height types (auto/custom/full) and updated `handleSectionBackground` to adjust logic based on these types. Enhanced flexibility for managing section height in layouts, with specific implementations in `MediaLayoutElement`.
> Add support for handling dynamic section height types.

- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/common/index.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
* Added a new test case (`ex47`) in `getText` tests to validate handling of Solstice-separated icons with empty text.
* Introduced `EMPTY_SPACES_REGEX` to match and remove various Unicode empty space characters, improving text normalization.
* Updated `getContainerStackWithNodes` to replace empty space characters using `EMPTY_SPACES_REGEX` before trimming text nodes, ensuring cleaner text extraction.
> fix(icons): icons are divided in two lines because of empty text

- lib/MBMigration/Builder/Layout/Common/Elements/Gallery/GalleryLayoutElement.php
Removed redundant and unused variables from GalleryLayoutElement to improve code clarity and maintainability. This cleanup eliminates unnecessary json_encode and BrizyComponent instantiations.
> refactor: remove unused variables in GalleryLayoutElement

- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/August/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Aurora/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Boulevard/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Dusk/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Hope/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Serene/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Tradition/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Zion/Elements/Head.php
Introduce `getThemeMenuItemActiveSelector` method across themes to define selectors for active menu items. This ensures consistency in handling active state styles and improves navigation functionality.
> feat: add active menu item selector for theme navigation

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
Introduce functionality to extract and handle deep slugs and full URLs. This ensures dynamic browser page opening based on menu and migration contexts, improving flexibility during layout transformations.
> feat: add support for dynamic page URL handling in migration

- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Builder/Utils/PathSlugExtractor.php
Replaced slug with id as the parameter for generating full URLs during page mapping. This ensures correct URL resolution by aligning with the intended method signature and logic.
> fix(page-mapping): correct parameter usage in URL generation

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Head.php
Extracted browser page handling logic from AbstractElement to Solstice Head element only. This improves encapsulation by localizing logic specific to the Solstice theme and prevents unnecessary duplication.
> refactor: move browser page logic to Solstice Head element

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/AccordionLayoutElement.php
Added left and right mobile padding with pixel suffixes to ensure consistent styling for accordion elements in the Anthem theme across mobile devices. This enhances the visual alignment and improves user experience on smaller screens.
> Set mobile padding for accordion section in Anthem theme

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Head.php
Enhanced hover menu styling by introducing the `isBgHoverItemMenu` method. Updated `evaluateScript` function to support additional hover style options for more flexible menu customization.
> Add hover menu style customization and `isBgHoverItemMenu` method

- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Text/ThreeHorizontalText.php
Introduced `getPropertiesMainSection` method to define mobile padding properties for the main section. Removed unused code handling section styles, streamlining the implementation.
> feat: add mobile padding properties for main section

- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Head.php
Changed logo sizeType from "custom" to "original" for correct scaling. Added additional size-related properties to improve layout rendering consistency.
> fix: update logo sizing to use original dimensions

- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Utils/ColorConverter.php
Introduced `normalizeColorEntry` and `isLikelyColor` methods to enhance default color fallbacks and opacity handling. Improved media element layout consistency by standardizing color and background property settings. Minor syntax adjustments for code readability.
> refactor: normalize color handling and improve opacity defaults
