- lib/MBMigration/Builder/ColorMapper/ChooseLargerContrast.php
- lib/MBMigration/Builder/ColorMapper/ContrastCalculate.php
- lib/MBMigration/Builder/Layout/Elements/DynamicElement/SermonLayoutPlaceholder.php
- lib/MBMigration/Builder/Layout/Elements/GridLayout.php
- fixed errors color and elements
> Refactoring:

- lib/MBMigration/Core/Config.php
- lib/MBMigration/Layer/MB/MBProjectDataCollector.php
- lib/MBMigration/MigrationPlatform.php
Refactoring:
- change in receiving the host project name
> Previwe base host name

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Globals.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Text.js
- package-lock.json
Added a null coalescing operator on 'data' field to return an empty array if 'data' is undefined. This adjustment enhances null safety in Anthem.php
> Return empty array if 'data' undefined in Anthem.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
A method to extract data from the page and update the SectionPage array has been added to streamline the data acquisition process. The color matching regular expression has been updated to specifically match rgb color codes, simplifying the code by removing unnecessary conditions and providing precise color matching functionality.
> Add data extraction method and modify color matching

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/GalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/TwoHorizontalText.php
- lib/MBMigration/Builder/PageBuilder.php
- lib/MBMigration/Core/Config.php
- lib/MBMigration/Core/ErrorDump.php
This update primarily improves the handling of unset variables and conditions for better error prevention. Multiple checks have been introduced for the existence of keys before trying to access their values. In addition, the code has been refactored for increased readability with the addition of return type definitions and the removal of unused imports.
> Update code to improve error handling and readability

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventCalendarLayout.php
The update includes refactoring of the Anthem theme components to enhance error handling and improve code readability, especially regarding content and filename checks. Furthermore, the mechanism for processing background color settings has been adjusted to directly use the background color from the section's style data.
> Refactor Anthem theme components and update color settings

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/dist/Menu.js
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/dist/Text.js
- packages/elements/src/Text/models/Text/index.ts
- packages/elements/src/types/global.d.ts
- packages/elements/src/utils/getData.ts
Rollback removedEmptyNodes https://github.com/bagrinsergiu/MB-Support/issues/162
> fix(text): rollback removedEmptyNodes

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/types/type.ts
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/src/types/type.ts
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/src/types/type.ts
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/src/types/type.ts
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/src/types/type.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/types/global.d.ts
- packages/elements/src/Text/models/Text/index.ts
- packages/elements/src/Text/utils/dom/removeEmptyNodes.ts
https://github.com/bagrinsergiu/MB-Support/issues/162
> fix(text): removed all p with \n

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/dist/Text.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/common/index.ts
- packages/elements/src/Text/utils/styles/copyParentColorToChild.ts
https://github.com/bagrinsergiu/MB-Support/issues/238#issuecomment-1914378051
> fix(text): font-weight italic

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/package.json
- package-lock.json
- package.json
> fix(package): linux with arm removed esbuild-arm

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/AccordionLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/FullText.php
Changes include commenting out donation related code in FullText.php for clear structure. Also, assignment of background color is modified in AccordionLayout.php, switching to use style.background-color from section data directly. These changes made to streamline code readability and improve maintainability.
> Refactor donation section and background color assignment

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Ember/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/dist/Text.js
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/dist/Text.js
- packages/elements/src/Text/models/Icon/utils/getModel.ts
Reverts bagrinsergiu/MB-migration#196
> Revert "added new icons - app store & google play"

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Accordion/index.ts
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/index.ts
- lib/MBMigration/Builder/Layout/Theme/Bloom/Assets/src/Menu/index.ts
| Q  | A |
| Screenshot  | ![Screenshot from 2024-02-28 16-26-10](https://github.com/bagrinsergiu/MB-migration/assets/40203375/cb23cc80-249b-49f5-9f2f-7256d6c26c95) |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/316 |
> refactor(accordion): added accordion to anthem script

- lib/MBMigration/Layer/Brizy/BrizyAPI.php
The error messages within the Brizy API class have been updated to include the result of the API response. These additional details will help in identifying the cause of the error more clearly and quickly.
> Improve Brizy API error messages

- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/305  |
> fix(text): fixed rich text content duplicating and not copying styles

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
Corrected the logic for determining 'new window' setting state and improved link handling in Element.php. Now, `new_window` accurately reflects if item opens in a new window, and URLs for external link types are more accurately detected and handled.
> Refactor new window setting and link processing logic

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Menu/index.ts
- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/src/Menu/utils/getModel.ts
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/src/Menu/index.ts
- lib/MBMigration/Builder/Layout/Theme/Majesty/Assets/src/Menu/utils/getModel.ts
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/src/Menu/index.ts
- lib/MBMigration/Builder/Layout/Theme/Solstice/Assets/src/Menu/utils/getModel.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/Menu/utils/getModel.ts
- packages/elements/src/Menu/getMenuItem.ts
- packages/elements/src/Menu/utils/dicKeyForDevices.ts
- packages/elements/src/Menu/utils/getModel.ts
- packages/utils/src/models/prefixed.ts
- packages/utils/src/text/capByPrefix.ts
| Q  | A |
| Screenshot  |  ![Screenshot from 2024-03-20 12-54-12](https://github.com/bagrinsergiu/MB-migration/assets/40203375/0cb9780b-632d-4c4e-a8e3-f7f57a2c2693) |
| Related tickets	  | https://github.com/bagrinsergiu/blox-editor/issues/25854 |
* Fix: no mobile/tablet keys for menu font
> fix(menu): no mobile/tablet keys for menu font

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Screenshot  | ![Screenshot from 2024-03-28 10-22-58](https://github.com/bagrinsergiu/MB-migration/assets/40203375/2228c952-70cd-4ecf-b6bf-f507b73b819b)  |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/331 |
* Fix : Anthem text duplicate content
> fix(text): anthem content duplicate text

- lib/MBMigration/Builder/Layout/Theme/Anthem/AnthemElementsController.php
A new dynamic element, PrayerForm, has been introduced to the Builder's Layout Theme Anthem. This revision changes the instantiation method in the case "prayer_form" from Form() to PrayerForm(), which will be used to handle relevant events.
> Add PrayerForm to AnthemElementsController

- .env.dev
- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Element.php
This commit refactors the code in Anthem element and Anthem file by introducing type hinting, improving style's opacity setting, restructuring the if-else condition blocks, and correcting the item content extraction. It also updates the database host in the .env.dev file.
> Refactor Anthem code and update environment variable

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/GridMediaLayout.php
This commit introduces new settings in the `GridMediaLayout` file for `parentCategory`, and `showCategoryFilter`. In addition, it enhances the color conversion logic in `Anthem` to handle opacity values, providing a smoother handling of style values.
> Added new settings and improved style conversion in Theme Builder

- lib/MBMigration/Builder/Layout/Theme/Anthem/Anthem.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/AnthemElementsController.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Sermons/GridMediaLayout.php
In this update, the title and hover color paths in GridMediaLayout are adjusted. Code related to ListMediaLayout in AnthemElementsController is removed. Furthermore, the string formatting for information and warning logs throughout the Anthem theme has been improved to enhance readability. The code handling 'grid-media-layout' or 'list-media-layout' in Anthem.php is also updated.
> Update styles and improve logging strings formatting in Anthem theme

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventLayout.php
The code has been updated to add hover settings to EventLayout. Specifically, settings to change color, opacity, and palette for event items on hover have been added. This will provide a better user experience as it will provide visual cues for interaction.
> Add hover settings to EventLayout

- lib/MBMigration/Builder/Fonts/FontsController.php
- lib/MBMigration/Builder/Layout/Common/Element/GalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/DynamicElements/Events/EventLayout.php
This update introduces several changes to layout elements including EventLayout, FontsController, and GalleryLayout. Changes include the enhancement of typography and color settings, and the introduction of a method to get font family from the name. The update also adds color settings for arrows and slider dots in GalleryLayout, and utilizes contrast color for better layout visibility.
> Update styling settings in layout elements

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/models/Button/utils/getModel.ts
| Q  | A |
| Screenshot  | ![2024-07-23_14-54](https://github.com/user-attachments/assets/19b2f1de-5f0b-478d-a66c-2986db2e8c0f)|
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/407 |
* Improved: added borderRadius to buttons
> refactor(button): added borderRadius to buttons

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/index.ts
- packages/elements/src/Text/models/Button/index.ts
- packages/elements/src/Text/models/Button/types.ts
- packages/elements/src/Text/models/Button/utils/getFontStyles.ts
- packages/elements/src/Text/models/Button/utils/getModel.ts
| Q  | A |
| Screenshot  |  ![2024-08-05_14-29](https://github.com/user-attachments/assets/c6fd51f5-a774-4785-90aa-c221a3bc3c35) |
| Screenshot  |  ![2024-08-05_14-46](https://github.com/user-attachments/assets/652619a8-cae6-4b92-8bf6-ffe10f7cf8d5) |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/400 |
> refactor(button): added fontSize, fontFamily and fontWeight values

- .env
- public/index.php
Updated `index.php` to include token-based authorization by comparing request token with the environment token. Added `APP_AUTHORIZATION_TOKEN` to the `.env` file to support this change.
> Add token-based authorization in index.php

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/models/Button/utils/getModel.ts
| Q  | A |
| Screenshot  | ![2024-09-05_11-22](https://github.com/user-attachments/assets/f5ec68df-14bc-4077-b3f8-956ab30cc984)|
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/400 |
> feat(button): added border color and width

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/422 | 
https://plumcreek.org/serve
https://www.rockhavenmonte.org/give
> fix(text): Button/links detection

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/models/Text/index.ts
- packages/elements/src/Text/utils/styles/addMarginsToLists.ts
| Q  | A |
| Related tickets | https://github.com/bagrinsergiu/MB-Support/issues/428 | 
Changelog
Fixed: Bullet points from list don't have any color applied
> fix(text): bullet points from list don't have any color

- lib/MBMigration/Browser/BrowserPagePHP.php
- lib/MBMigration/Builder/Layout/Common/Concern/BrizyQueryBuilderAware.php
- lib/MBMigration/Builder/Layout/Common/Element/GridLayout.php
- lib/MBMigration/Builder/Layout/Common/Element/Sermons/MediaLayout.php
- lib/MBMigration/Builder/Layout/Common/ThemeContext.php
- lib/MBMigration/Builder/Layout/Common/ThemeContextInterface.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
- lib/MBMigration/Builder/PageController.php
Add browser interface to ThemeContext and improve `Head` handling
Integrate `BrowserInterface` into `ThemeContext` to streamline browser interactions across the project. Adjust Head element transformation to utilize the new browser functionalities, ensuring cleaner and more efficient code. Reduce sleep time in browser actions to expedite operations.
> 440 42 anthem header updates missing

- lib/MBMigration/Builder/Layout/Common/Concern/ImageStylesAble.php
- lib/MBMigration/Builder/Layout/Common/Element/GridLayout.php
- lib/MBMigration/Builder/Utils/ColorConverter.php
Implemented handling for image style properties in GridLayout using the new ImageStylesAble concern. Enhanced the handleBgPhotoItems method to accept additional options and adjusted method visibility in the ColorConverter class.
> Add image styling to GridLayout

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/utils/src/dom/extractAllElementsStyles.ts
| Q  | A |
| Screenshot | N/A|
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/448 |
* Fixed:  Voyage font weight issue
> fix(text): voyage font weight issue

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
Updated the active menu border color to match the menu text color dynamically. Introduced new padding configurations for better menu item spacing.
> Set dynamic text color for active menu border and add padding

- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/index.ts
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/AccordionLayoutElement.php
Implemented internal transformation logic in AccordionLayoutElement to handle section styles and element context. Added utility functions and external dependencies to support the transformation process. Updated index.ts to import accordion run method for proper initialization.
> Add internal transformation for Accordion layout

- lib/MBMigration/Builder/Layout/Theme/Voyage/Assets/src/Accordion/index.ts
- packages/elements/src/Accordion/index.ts
- packages/elements/src/Accordion/models.ts
- packages/elements/src/Tabs/__tests__/getTabs.ts
- packages/elements/src/Tabs/index.ts
- packages/elements/src/Tabs/models.ts
- packages/elements/src/utils/getModel.ts
| Q  | A |
| Screenshot  | ![chrome_eatGTeDWkG](https://github.com/user-attachments/assets/bc5a1267-a4c3-4c93-817b-f81597b2a663)|
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/444  |
* Improved: Added bg keys for accordion
> refactor(accordion): added bg keys

- lib/MBMigration/Builder/Layout/Common/MenuBuilder.php
Changed `textTransform` to an array to handle different transformations for main and submenus. Updated methods to pass and use the appropriate text transformation based on the menu type.
> Refactor MenuBuilder for text transform per menu type

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
Consolidated row size and mobile size setting into a single method chain for better readability and maintainability. This change removes conditional checks and streamlines the size assignment process.
> Refactor size setting in GridLayoutElement

- lib/MBMigration/Builder/Layout/Common/Concern/DanationsAble.php
Added logic to set text-transform properties (uppercase, lowercase, none) for the donation button. Improved handling of color palette settings, including hover states and default alignments for cases where no specific alignment is set.
> Enhance donation button styling and text transform handling

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Screenshot  | ![2024-10-25_10-49](https://github.com/user-attachments/assets/0f66d71f-75cc-4cb4-84c5-723787b39288) |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/472 |
* Fixed:RichText embed detection
> fix(richtext): embed detection

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
Introduce a new sectionRowPadding array with customized padding settings. Adjust foreach loops to apply these settings along with existing configurations to the brizySection item at the specified depths.
> Add section row padding configuration to Head element.

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Screenshot  |  ![2024-10-24_16-28](https://github.com/user-attachments/assets/cd0f371f-49c6-4c95-8d6a-c6881b19a5ca) | 
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/473 |
* Fixed : wrong icon aligment
> fix(richtext): wrong icon aligment

- lib/MBMigration/Builder/Layout/Theme/Anthem/Assets/dist/index.js
- packages/elements/src/Text/__tests__/getText.ts
- packages/elements/src/Text/utils/dom/getContainerStackWithNodes.ts
| Q  | A |
| Screenshot  | ![2024-10-29_12-37](https://github.com/user-attachments/assets/f3b75466-a680-40eb-86fe-78b2400d3c61) |
| Related tickets	  | https://github.com/bagrinsergiu/MB-Support/issues/484 |
* Fixed: RichText wrong tags
> fix(richtext): Text wrong tags

- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/August/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Aurora/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Boulevard/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Dusk/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Hope/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Serene/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Tradition/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Zion/Elements/Head.php
Refactor submenu item selectors to differentiate between selected and non-selected items. Introduced methods to handle CSS class for selected submenu items and updated the script execution logic to account for errors and apply/remove classes accordingly.
> Update submenu selector handling for various themes

- lib/MBMigration/Builder/Layout/Common/ThemeContext.php
- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Core/Config.php
- lib/MBMigration/Layer/Brizy/BrizyAPI.php
- lib/MBMigration/Layer/MB/MonkcmsAPI.php
- lib/MBMigration/MigrationPlatform.php
Increased mobile padding values from 25px/20px to 50px across multiple elements. Adjusted button background and text color settings for better consistency with the section palette.
> Update mobile padding and button color settings

- lib/MBMigration/Builder/Layout/Common/Concern/DanationsAble.php
Refactored to set button text to uppercase or lowercase based on settings. Utilized strtoupper and strtolower functions to ensure correct text transformation. Adjusted final assignment to use transformed buttonText variable.
> Update text case handling in DanationsAble

- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Builder/Utils/UrlUtils.php
Introduce a UrlUtils class to check for URL redirects using cURL. Update PageController to incorporate this feature, ensuring that pages with redirects are handled appropriately. Enhance timeout exception handling by closing the browser page and instance before retrying to open a page.
> Add URL redirect check and handle timeout exceptions

- composer.json
- lib/MBMigration/Builder/Media/MediaController.php
- lib/MBMigration/Layer/Brizy/BrizyAPI.php
Introduced a method to resize images exceeding the specified size limit. Enhanced robustness by ensuring unsupported image types are identified, and logs are added for debugging purposes. Additionally, fixed minor typos and improved logging in other related functions.
> feat: add image resizing for oversized files

- Dockerfile
- lib/MBMigration/Layer/Brizy/BrizyAPI.php
Add image format conversion and improved error handling in BrizyAPI. Update Dockerfile to configure PHP GD with JPEG and Freetype support, ensuring compatibility and robustness for image handling workflows.
> feat: enhance image processing and GD support

- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Footer.php
Added handling of additional style options by merging theme context page details with main section properties. This enhances the flexibility of footer styling within the layout.
> feat: add support for additional style options in footer

- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FourHorizontalText.php
Introduce the ButtonAble trait to enhance button handling functionality. Updated logic to check for and handle button elements within the FourHorizontalText component. Removed redundant donations handling in the transformation process.
> feat: add ButtonAble trait and handle buttons in FourHorizontalText

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/GridLayoutElement.php
Reverts bagrinsergiu/MB-migration#471
> Revert "feat(padding): add reusable handleItemRowComponent method"

- lib/MBMigration/Builder/Layout/Common/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/GridLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/GridLayoutElement.php
Reverts bagrinsergiu/MB-migration#472
> Revert "Revert "feat(padding): add reusable handleItemRowComponent method""

- lib/MBMigration/Builder/Layout/Common/Concern/ButtonAble.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/FourHorizontalText.php
- lib/MBMigration/Builder/Utils/ColorConverter.php
Introduced caching for button elements to reduce redundant processing and enhance performance. Updated color handling logic for better accuracy and consistency, particularly for border and hover styles. Refactored related code for maintainability and readability.
> Add button caching and improve color handling logic

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Text/ListLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Forms/FullWidthForm.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Forms/LeftForm.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Forms/RightForm.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Groups/SmallGroupsListElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Prayer/PrayerFormElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Prayer/PrayerListElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Text/ListLayoutElement.php
Updated default padding values across multiple components for consistency, including top and mobile paddings. Added new method `handleRowListItem` for uniform row styling and enhanced section style handling with additional theme context options.
> feat: adjust default paddings and enhance style handling

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventDetailsPageLayout.php
Updated typography methods to accept customizable parameters, enabling more precise control over lineHeight and other properties. Refactored `EventDetailsPageLayout` to align with these updates, improving maintainability and consistency in styling logic.
> refactor: enhance typography configuration flexibility

- lib/MBMigration/Browser/BrowserPHP.php
- lib/MBMigration/Browser/BrowserPagePHP.php
- lib/MBMigration/Builder/Layout/Common/Concern/ButtonAble.php
- lib/MBMigration/Builder/Layout/Common/DTO/PageDto.php
- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/DetailsPage.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventDetailsPageLayout.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventFeaturedLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Common/Objects/Button/ButtonStyle.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Ember/Elements/Events/EventLayoutElement.php
- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Builder/Utils/ColorConverter.php
- lib/MBMigration/Builder/Utils/PathSlugExtractor.php
- lib/MBMigration/Builder/Utils/UrlBuilder.php
Introduced methods to extract normal and hover styles for buttons using CSS properties. Enhanced button handling logic by incorporating new concerns and utilities within ButtonAble. Adjusted browser configurations to accommodate style extraction and added logging for button hover events.
> feat(buttons): add support for extracting button styles

- lib/MBMigration/Layer/Brizy/BrizyAPI.php
Refactor image handling to include enhanced error checking and better conversion logic. Updated methods to return detailed status arrays instead of strings for better context. Improved logging clarity and added more robust handling for unsupported formats and file issues.
> refactor: improve image processing and error handling

- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Head.php
Added functionality to remove a CSS class from selected submenu items and introduced a new method to retrieve the selector for selected submenu items. Cleaned up redundant code and adjusted hover handling for improved consistency.
> feat: enhance submenu item handling in Head element

- lib/MBMigration/Browser/BrowserPageInterface.php
- lib/MBMigration/Browser/BrowserPagePHP.php
- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Head.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Head.php
Introduce ThemeContextInterface property and related logic to elements for better theme handling. Updated browser page screenshot method to support filename prefixing. Improved menu item and sub-menu item handling across various themes with added selectors and transformations.
> feat: enhance browser page handling and add theme context support

- lib/MBMigration/Builder/Layout/Common/Concern/RichTextAble.php
- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
Added custom font-face CSS for social icons and adjusted `overflow` setting for embedded components. These changes address styling issues with icons in embed code and improve layout consistency in rich text sections.
> fix: improve CSS handling for rich text and embedded elements

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/ListLayoutElement.php
Introduced an `addMargin` method in BrizyComponent to handle margin configuration. Also updated ListLayoutElement to use the new method for row list item styling.
> feat: add margin functionality to BrizyComponent

- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Layer/MB/MBProjectDataCollector.php
Refactored the home page creation logic to ensure proper handling of `isHome` flag and avoided redundant conditions. Simplified logging by removing duplicate log entries and clarifying critical exceptions for missing projects or domains.
> `fix: handle home page creation and refine error logging`

- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventGalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Events/EventGalleryLayout.php
Updated the top padding of the first element to 200 for consistency. Added typography-related setup for better detail and styling of event gallery components.
> feat: adjust top padding and enhance typography setup

- .env
- composer.json
- composer.lock
- lib/MBMigration/Core/S3Uploader.php
- public/index.php
Introduces `S3Uploader` to upload migration logs to an S3 bucket when enabled. Updated `composer.json` to include the AWS SDK and adjusted the log management in the main processing flow to generate and upload log files. Added `AWS_BUCKET_ACTIVE` and related configuration to `.env`.
> feat: add S3 log upload functionality for migrations

- lib/MBMigration/Core/ErrorDump.php
- lib/MBMigration/MigrationPlatform.php
- public/index.php
Introduce handling for uncaught exceptions by implementing a custom exception handler in `ErrorDump`. This ensures better error tracking and logging during runtime. Additionally, minor syntax corrections were made to improve code consistency.
> feat(error-handling): add uncaught exception handler

- lib/MBMigration/Builder/Fonts/FontsController.php
- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Layer/MB/MBProjectDataCollector.php
- lib/MBMigration/Layer/MB/MonkcmsAPI.php
- public/index.php
Introduces advanced font handling by merging custom and snippet fonts, improves project font data extraction, and refactors font-related methods for clarity. Also adds functionality to the `MonkcmsAPI` for retrieving group series by slug, extending CMS API support. Minor code cleanup includes consistent formatting and updated method names.
> feat: enhance font management and add group series handling

- lib/MBMigration/Builder/Layout/Common/Concern/SectionStylesAble.php
https://github.com/bagrinsergiu/MB-Support/issues/592
> Update background image handling in SectionStylesAble

- lib/MBMigration/Builder/Layout/Theme/Bloom/Elements/Text/AccordionLayoutElement.php
Introduced a new mobile padding configuration for accordion elements to enhance responsiveness. The padding values are set dynamically through a loop to ensure consistent application of styles.
> feat: add mobile padding styling to accordion layout

- lib/MBMigration/Builder/Layout/Common/AbstractTheme.php
- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventGalleryLayout.php
- lib/MBMigration/Builder/Layout/Theme/Bloom/ElementFactory.php
Ensure correct handling of multiple 'event' sections by introducing a consolidated 'event-calendar-layout'. Adjust element factory and widget methods for consistent event detail processing and proper property assignment.
> fix: handle multiple event sections and layout processing

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Events/EventFeturedLayout.php
Updated padding values in AbstractElement and EventFeaturedLayout to improve visual alignment and spacing. These changes ensure a more cohesive and consistent design across different components.
> fix: adjust padding for layout consistency

- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Text/ListLayoutElement.php
https://github.com/bagrinsergiu/MB-Support/issues/600
> Anthem - mobile - column border update for white page background #600

- lib/MBMigration/Builder/Layout/Common/Concern/RichTextAble.php
- lib/MBMigration/Builder/Media/MediaController.php
Introduce `getMediaURL` for dynamic media URL generation. Add `isVideo` to detect video files and enhance existing link handling for media types. Refactor methods for better readability and consistency.
> feat(media): add video handling and media URL generation

- lib/MBMigration/Builder/Layout/Common/Concern/DonationsAble.php
Refactored donation button styling logic including alignment, padding, and hover functionality for better readability and maintainability. Updated selector formatting and added fallback values for padding to ensure consistent styling. Introduced slight delays for hover simulations and improved handling of hover opacity defaults.
> refactor: improve donation button style handling

- lib/MBMigration/Builder/Layout/Common/Elements/Text/TabsLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Voyage/Elements/Text/TabsLayoutElement.php
Updated mobile margin values to fix layout inconsistencies and introduced a custom CSS method for enhanced tabs styling. These changes improve visual alignment and maintain consistency across different sections.
> fix: adjust mobile margins and add custom CSS for tabs

- lib/MBMigration/Builder/Layout/Common/Elements/AbstractElement.php
- lib/MBMigration/Builder/Layout/Common/Elements/Sermons/MediaLayoutElement.php
- lib/MBMigration/Builder/Layout/Theme/Anthem/Elements/Sermons/MediaLayoutElement.php
Introduced a method to calculate additional top padding for detail pages. Updated constructor to handle exceptions with proper logging and improved item transformation logic for MediaLayoutElement.
> feat: add support for additional top padding in detail pages

- lib/MBMigration/Builder/Layout/Common/Elements/Events/EventLayoutElement.php
Adjusted `hoverViewColorOpacity` and `viewColorOpacity` values to improve consistency. Added new `activeViewColor*` properties to enhance layout customization options. These changes aim to provide better control over event layout styling.
>  feat(event-layout): update color opacity and add active view

- lib/MBMigration/Builder/Layout/Common/Concern/SectionStylesAble.php
Added support for mobile background size, size type, and repeat settings. This enhances customization options for section designs on mobile devices.
> feat: add mobile background styling options to sections

- lib/MBMigration/Builder/Layout/Common/Template/DetailPages/EventDetailsPageLayout.php
- lib/MBMigration/Builder/Layout/Common/Template/DetailPages/SermonDetailsPageLayout.php
- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Head.php
Adjusted color fallback logic to prioritize 'btn-text' over 'text' for consistency. Removed redundant opacity definitions and added a new method to set left margin for mobile layouts. This improves maintainability and ensures better alignment across components.
> refactor: simplify color handling and update margin logic

- lib/MBMigration/Builder/Layout/Common/Elements/Text/PhotoTextElement.php
- lib/MBMigration/Builder/Layout/Theme/Majesty/ElementFactory.php
- lib/MBMigration/Builder/Media/MediaController.php
- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Builder/Utils/ArrayManipulator.php
- lib/MBMigration/Layer/MB/MBProjectDataCollector.php
Introduced a new 'gallery' section in the PageController and updated the MediaController to handle gallery items. Enhanced the PhotoTextElement to support 'left-gallery' type sections, ensuring proper item processing. Updated ArrayManipulator to accommodate new gallery logic and improved logging in MediaController for better tracking of media uploads.
> feat: add gallery support and enhance media handling

- lib/MBMigration/Builder/Layout/Common/Elements/HeadElement.php
- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Head.php
Improved handling of submenu item styles by updating selectors and utilizing the `ColorConverter` utility for color conversion. Replaced hardcoded submenu logic with a more dynamic and efficient approach. These changes enhance maintainability and accuracy in rendering styles.
> fix: refine submenu item style handling and selector logic

- lib/MBMigration/Builder/Layout/Theme/Solstice/Elements/Text/AccordionLayoutElement.php
Enhanced the accordion element styles by adding `borderWidthType`, `borderStyle`, `borderBottomWidth`, and negative `spacing` configurations to improve layout customization.
> Add border style and spacing configurations for accordion elements

- lib/MBMigration/WaveProc.php
Added detailed logging with a new Logger class to improve traceability of migrations. Enhanced error handling and improved diagnostics for cURL requests, file operations, and JSON processing.
> feat(logging): integrate enhanced logging in WaveProc

- lib/MBMigration/Builder/BrizyComponent/BrizyComponent.php
- lib/MBMigration/Builder/Fonts/FontsController.php
- lib/MBMigration/Builder/Layout/Theme/Majesty/Elements/Footer.php
- lib/MBMigration/Builder/PageController.php
- lib/MBMigration/Layer/Brizy/BrizyAPI.php
Refactored `createFonts` and related methods to improve error handling, logging, and support for comprehensive font presence checks. Added new methods like `logFontPresenceIfExists` and detailed logging for font operations across upload and migration workflows. Enhanced project data validation and streamlined font upload processes for better reliability.
> feat: enhance font upload workflow and logging
